### ISSUE TITLE
CI Builds for Packages

### ISSUE THREAD

**Issue by iwillspeak** [iwillspeak/IronRure-Batteries#4]
Create appveyor builds for Linux, Windows and macOS which compile `rure` and build the package.

 * [x] Windows
 * [x] Linux
 * [x] macOS

**Comment by hanabi1224** [comment]
@iwillspeak  I just sent a PR for windows CI on appveyor, can you take a look?

**Comment by iwillspeak** [comment]
Nice one!

**Comment by hanabi1224** [comment]
@iwillspeak   sent a PR for linux CI as well

**Comment by iwillspeak** [comment]
Thanks for your work on this @hanabi1224. I _think_ macOS is just a matter of adding a target to Appveyor for it. I've set up a build for the project at <https://ci.appveyor.com/project/iwillspeak/ironrure-batteries>. The CI build NuGet package feed is at <https://ci.appveyor.com/nuget/ironrure-batteries-s458herorymt>.

**Comment by iwillspeak** [comment]
I'll have a go at configuring this for macOS tomorrow morning. Given how infrequently new builds of the batteries are needed I think we can live with having to download the artifact from Appveyor manually and uploading them to NuGet.org.

**Comment by iwillspeak** [comment]
My bad. It is VSTS not AppVeyor that has macOS boxes. Might have to use Travis instead. Either that or we move all the builds to VSTS.

**Comment by hanabi1224** [comment]
@iwillspeak  I think travis supports osx build, just sent a PR https://github.com/iwillspeak/IronRure-Batteries/pull/8   You may need to setup artifact for ur repo later
